version: '3'
services:
  node:
    build: ./Reverse_proxy
    restart: always
    ports:
      - "8000:8000"
  web:
    build: ./Application
    ports:
     - "8080:8080"
    volumes:
     - ./Application:/home/app

